config/routes.rb
Bowler::Application.routes.draw do
  resources :bowls

  root 'bowls#index'

  match '/bowl/reset', to: 'bowls#reset', via: :delete

 

end

app/models/bowl.rb
class Bowl < ActiveRecord::Base
	belongs_to :player
   

    # Bowling happens here
	def roll(player_id)  	
		pins_hit = rand(1..10) # 1 more likely to get spare :)
		
		if first_roll?(player_id) && pins_hit == 10 # strike
			self.score = 10
			self.turn += 2 # Next Frame
		elsif first_roll?(player_id) 
			self.score = pins_hit
			self.turn += 1
		else
			self.score = 0
			pins_hit = rand(1..pins_left(player_id)) # 1 more likely to get spare :)
	   		self.score += pins_hit
			self.turn += 1

		end		
		# strike spare adds points for strikes and spares depending on next frame	
		self.strike_spare = spare_points(player_id)
		self.strike_spare += strike_points(player_id)

	end

	def first_roll?(player_id)
		turn_array(player_id).reduce(:+).nil? ? true : first_roll(player_id)
	end

	def self.total_score(player_id)
		if Bowl.new.num_rolls(player_id) > 2 # NilClass Error if less than 2 
			Bowl.where(:player_id => player_id).all.map(&:strike_spare).reduce(:+) + Bowl.where(:player_id => player_id).all.map(&:score).reduce(:+)
		else 
			Bowl.where(:player_id => player_id).all.map(&:score).reduce(:+)
		end
	end

	def spare?(player_id) 
		 scores_array(player_id).last(2).reduce(:+) == 10 && first_roll(player_id) unless scores_array(player_id).length <= 1
	end

	def first_roll(player_id)
		num_rolls(player_id) % 2 == 0 # strike = 2
	end

	def spare_points(player_id) 
		if num_rolls(player_id) > 3
			was_spare = scores_array(player_id)[-3..-2].reduce(:+) == 10 && !first_roll(player_id)
		elsif num_rolls(player_id) == 3 
			was_spare = scores_array(player_id)[0..1].reduce(:+) == 10
		else
			was_spare = false
		end
		was_spare ? scores_array(player_id)[-1] : 0 # return last score if was spare
				
	end

	def strike?(player_id)
		scores_array(player_id).last == 10 
	end

	def strike_points(player_id)
		was_strike = scores_array(player_id)[-3] == 10 if num_rolls(player_id) >= 3 
		was_strike ? scores_array(player_id)[-2..-1].reduce(:+) : 0
	end

	def last_frame
		strike? ? scores_array(player_id).last : scores_array(player_id).last(2).reduce(:+)
	end


	def frame_number(player_id)
		# no more than ten frames
		if num_rolls(player_id) >= 20
			10
		elsif num_rolls(player_id).nil?
			0
		else
			num_rolls(player_id) / 2 + 1
		end
	end

	def num_rolls(player_id)
		turn_array(player_id).empty? ? 0 : turn_array(player_id).reduce(:+)
	end

	def turn_array(player_id)
		Bowl.where(:player_id => player_id).all.map(&:turn) # array of rolls strike = 2 rolls
	end

	def scores_array(player_id)
		Bowl.where(:player_id => player_id).all.map(&:score) # array of scores w/o strikes and spares
	end

	def pins_left(player_id)
		10 - (scores_array(player_id).last)
	end

    
end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :bowls
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/bowls_controller.rb
class BowlsController < ApplicationController
  before_action :set_bowl, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js

  # GET /bowls
  # GET /bowls.json
  def index
    @p1_bowls = Bowl.where(player_id: 1)
    @p2_bowls = Bowl.where(player_id: 2)
    @bowls = Bowl.all
    @bowl = Bowl.new
    @total_score_p1 = @bowls.total_score(1)
    @total_score_p2 = @bowls.total_score(2)
    @total_turns_p1 = @bowls.where(player_id: 1).map(&:turn).reduce(:+)
    @total_turns_p2 = @bowls.where(player_id: 2).map(&:turn).reduce(:+)
    @frame_p1 = @bowl.frame_number(1)
    @frame_p2 = @bowl.frame_number(2)
  end

  def reset
    Bowl.destroy_all
    redirect_to root_path
  end


  # POST /bowls
  # POST /bowls.json
  def create
    @bowl = Bowl.new(bowl_params)
    @bowl.player = Player.find(params[:player_id])
    # Player Rolls - ID param is passed
    @bowl.roll(params[:player_id])


    respond_to do |format|
      if @bowl.save
        format.html { redirect_to root_path, notice: 'Bowl was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bowl }
      else
        format.html { render action: 'new' }
        format.json { render json: @bowl.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /bowls/1
  # DELETE /bowls/1.json
  def destroy
    @bowl.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bowl
      @bowl = Bowl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bowl_params
      
      params.fetch(:bowl, {}).permit(:score, :total_score, :turn)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bowls_helper.rb
module BowlsHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/bowls/_bowl.html.erb
<div class="scoreboard">
    <div class="frame_num">
      <%= "FRAME: #{@frame_p1} - " %>
      <% if @total_turns_p1.nil? ? false : @total_turns_p1 % 2 == 1  %>
        <%= "Pins Remaining: #{10 - Bowl.where(:player_id => 1).all.map(&:score).last}" %>
      <% elsif @total_turns_p1 == 20 %>
         Last Roll
      <% else %>
         First Roll
      <% end %> 
    </div>            
</div> 
    
<div class="frame">          
   <% @p1_bowls.each do |bowl| %>
        <div class="score"><%= "#{bowl.score}" %></div>            
   <% end %>
   <div class="frame_num">
     <%= "Strike!!" if @p1_bowls.last.strike?(1) unless @p1_bowls.last.nil? %>
     <%= "Spare!!" if @p1_bowls.last.spare?(1) unless @p1_bowls.last.nil? %>
   </div> 
  
  <div class="total">
    <%= @total_score_p1 %>
  </div>
</div>

<div class="scoreboard">
      <div class="frame_num">
        <%= "FRAME: #{@frame_p2} - " %>
        <% if @total_turns_p2.nil? ? false : @total_turns_p2 % 2 == 1  %>
          <%= "Pins Remaining: #{10 - Bowl.where(:player_id => 2).all.map(&:score).last}" %>
        <% elsif @total_turns_p2 == 20 %>
           Last Roll
        <% else %>
           First Roll
        <% end %> 
      </div>   
</div> 

<div class="frame">
 <% @p2_bowls.each do |bowl| %>                
      <div class="score"><%= "#{bowl.score}" %></div>    
 <% end %>
 <div class="frame_num">
  <%= "Strike!!" if @p2_bowls.last.strike?(2) unless @p2_bowls.last.nil? %>
  <%= "Spare!!" if @p2_bowls.last.spare?(2) unless @p2_bowls.last.nil? %>
 </div> 
        
  <div class="total">
    <%= @total_score_p2 %>
  </div>
</div>

app/views/bowls/_form.html.erb
<div class="submit-roll">
<!-- 
 Hidden Field Tag Player One -->
  <%= form_for @bowl, remote: true do |f| %>
    <%= hidden_field_tag :player_id, 1 %>
  
      
     <% if @total_turns_p1.nil? || @total_turns_p1 < 20  %>
      <h1>Player One</h1>       
      <%= f.submit "Roll!" %>
     <% elsif @total_turns_p1 == 20 && @bowls.where(:player_id => 1).map(&:score).last(2).reduce(:+) == 10  %>
       <%= f.submit "Roll!" %>      
     <% else %>
        <h1>Play Again?</h1>
     <% end %>
    

  <% end %>
</div>

<div class="submit-roll">
<!-- , remote: true -->

<!-- 
 Hidden Field Tag Player Two -->
<%= form_for @bowl, remote: true do |f| %>
  <%= hidden_field_tag :player_id, 2 %>
  
  <div id="ajax-form">  
    <% if @total_turns_p2.nil? || @total_turns_p2 < 20  %>
      <h1>Player Two</h1>
       
        <%= f.submit "Roll!" %>
    <% elsif @total_turns == 20 && @bowls.where(:player_id => 2).map(&:score).last(2).reduce(:+) == 10  %>
       
        <%= f.submit "Roll!" %>      
    <% else %>
        <h1>Play Again?</h1>
    <% end %>
  </div>

<% end %>
</div>

app/views/bowls/index.html.erb
<h1>An Amazing Bowling App</h1>

<!-- AJAX render bowl -->
<div id="box-score"> 
  <%= render 'bowl' %>
</div><br>

<!-- AJAX render form -->
<div id="roll">
  <%= render 'form' %>
</div>

<br>
<br>


<%= button_to 'Reset', bowl_reset_path, method: :delete, confirm: 'Bad Frame?', class: "reset-button" %>


<!-- # <%= link_to 'New Bowl', new_bowl_path %> -->

app/views/bowls/index.js.erb
// # A Little AJAX for better UI 
$('#box-score').html('<%= j render 'bowl' %>');
$("#roll").html('<%= j render 'form' %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bowler</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>